export const MOCK_GITHUB_USERS_BY_USERNAME = {
    data: {
        total_count: 327124,
        incomplete_results: false,
        items: [
            {
                login: 'john',
                id: 1668,
                node_id: 'MDQ6VXNlcjE2Njg=',
                avatar_url: 'https://avatars.githubusercontent.com/u/1668?v=4',
                gravatar_id: '',
                url: 'https://api.github.com/users/john',
                html_url: 'https://github.com/john',
                followers_url: 'https://api.github.com/users/john/followers',
                following_url: 'https://api.github.com/users/john/following{/other_user}',
                gists_url: 'https://api.github.com/users/john/gists{/gist_id}',
                starred_url: 'https://api.github.com/users/john/starred{/owner}{/repo}',
                subscriptions_url: 'https://api.github.com/users/john/subscriptions',
                organizations_url: 'https://api.github.com/users/john/orgs',
                repos_url: 'https://api.github.com/users/john/repos',
                events_url: 'https://api.github.com/users/john/events{/privacy}',
                received_events_url: 'https://api.github.com/users/john/received_events',
                type: 'User',
                user_view_type: 'public',
                site_admin: false,
                score: 1.0,
            },
            {
                login: 'john-smilga',
                id: 42133389,
                node_id: 'MDQ6VXNlcjQyMTMzMzg5',
                avatar_url: 'https://avatars.githubusercontent.com/u/42133389?v=4',
                gravatar_id: '',
                url: 'https://api.github.com/users/john-smilga',
                html_url: 'https://github.com/john-smilga',
                followers_url: 'https://api.github.com/users/john-smilga/followers',
                following_url: 'https://api.github.com/users/john-smilga/following{/other_user}',
                gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
                starred_url: 'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
                subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
                organizations_url: 'https://api.github.com/users/john-smilga/orgs',
                repos_url: 'https://api.github.com/users/john-smilga/repos',
                events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
                received_events_url: 'https://api.github.com/users/john-smilga/received_events',
                type: 'User',
                user_view_type: 'public',
                site_admin: false,
                score: 1.0,
            },
            {
                login: 'JohnMwendwa',
                id: 72663882,
                node_id: 'MDQ6VXNlcjcyNjYzODgy',
                avatar_url: 'https://avatars.githubusercontent.com/u/72663882?v=4',
                gravatar_id: '',
                url: 'https://api.github.com/users/JohnMwendwa',
                html_url: 'https://github.com/JohnMwendwa',
                followers_url: 'https://api.github.com/users/JohnMwendwa/followers',
                following_url: 'https://api.github.com/users/JohnMwendwa/following{/other_user}',
                gists_url: 'https://api.github.com/users/JohnMwendwa/gists{/gist_id}',
                starred_url: 'https://api.github.com/users/JohnMwendwa/starred{/owner}{/repo}',
                subscriptions_url: 'https://api.github.com/users/JohnMwendwa/subscriptions',
                organizations_url: 'https://api.github.com/users/JohnMwendwa/orgs',
                repos_url: 'https://api.github.com/users/JohnMwendwa/repos',
                events_url: 'https://api.github.com/users/JohnMwendwa/events{/privacy}',
                received_events_url: 'https://api.github.com/users/JohnMwendwa/received_events',
                type: 'User',
                user_view_type: 'public',
                site_admin: false,
                score: 1.0,
            },
        ],
    },
};

export const MOCK_GITHUB_REPOSITORIES_BY_USERNAMES = {
    data: [
        {
            repositories: [
                {
                    id: 528654,
                    node_id: 'MDEwOlJlcG9zaXRvcnk1Mjg2NTQ=',
                    name: 'canopy',
                    full_name: 'duy/canopy',
                    private: false,
                    owner: {
                        login: 'duy',
                        id: 77944,
                        node_id: 'MDQ6VXNlcjc3OTQ0',
                        avatar_url: 'https://avatars.githubusercontent.com/u/77944?v=4',
                        gravatar_id: '',
                        url: 'https://api.github.com/users/duy',
                        html_url: 'https://github.com/duy',
                        followers_url: 'https://api.github.com/users/duy/followers',
                        following_url: 'https://api.github.com/users/duy/following{/other_user}',
                        gists_url: 'https://api.github.com/users/duy/gists{/gist_id}',
                        starred_url: 'https://api.github.com/users/duy/starred{/owner}{/repo}',
                        subscriptions_url: 'https://api.github.com/users/duy/subscriptions',
                        organizations_url: 'https://api.github.com/users/duy/orgs',
                        repos_url: 'https://api.github.com/users/duy/repos',
                        events_url: 'https://api.github.com/users/duy/events{/privacy}',
                        received_events_url: 'https://api.github.com/users/duy/received_events',
                        type: 'User',
                        user_view_type: 'public',
                        site_admin: false,
                    },
                    html_url: 'https://github.com/duy/canopy',
                    description: 'django frontend for Tahoe-LAFS',
                    fork: true,
                    url: 'https://api.github.com/repos/duy/canopy',
                    forks_url: 'https://api.github.com/repos/duy/canopy/forks',
                    keys_url: 'https://api.github.com/repos/duy/canopy/keys{/key_id}',
                    collaborators_url: 'https://api.github.com/repos/duy/canopy/collaborators{/collaborator}',
                    teams_url: 'https://api.github.com/repos/duy/canopy/teams',
                    hooks_url: 'https://api.github.com/repos/duy/canopy/hooks',
                    issue_events_url: 'https://api.github.com/repos/duy/canopy/issues/events{/number}',
                    events_url: 'https://api.github.com/repos/duy/canopy/events',
                    assignees_url: 'https://api.github.com/repos/duy/canopy/assignees{/user}',
                    branches_url: 'https://api.github.com/repos/duy/canopy/branches{/branch}',
                    tags_url: 'https://api.github.com/repos/duy/canopy/tags',
                    blobs_url: 'https://api.github.com/repos/duy/canopy/git/blobs{/sha}',
                    git_tags_url: 'https://api.github.com/repos/duy/canopy/git/tags{/sha}',
                    git_refs_url: 'https://api.github.com/repos/duy/canopy/git/refs{/sha}',
                    trees_url: 'https://api.github.com/repos/duy/canopy/git/trees{/sha}',
                    statuses_url: 'https://api.github.com/repos/duy/canopy/statuses/{sha}',
                    languages_url: 'https://api.github.com/repos/duy/canopy/languages',
                    stargazers_url: 'https://api.github.com/repos/duy/canopy/stargazers',
                    contributors_url: 'https://api.github.com/repos/duy/canopy/contributors',
                    subscribers_url: 'https://api.github.com/repos/duy/canopy/subscribers',
                    subscription_url: 'https://api.github.com/repos/duy/canopy/subscription',
                    commits_url: 'https://api.github.com/repos/duy/canopy/commits{/sha}',
                    git_commits_url: 'https://api.github.com/repos/duy/canopy/git/commits{/sha}',
                    comments_url: 'https://api.github.com/repos/duy/canopy/comments{/number}',
                    issue_comment_url: 'https://api.github.com/repos/duy/canopy/issues/comments{/number}',
                    contents_url: 'https://api.github.com/repos/duy/canopy/contents/{+path}',
                    compare_url: 'https://api.github.com/repos/duy/canopy/compare/{base}...{head}',
                    merges_url: 'https://api.github.com/repos/duy/canopy/merges',
                    archive_url: 'https://api.github.com/repos/duy/canopy/{archive_format}{/ref}',
                    downloads_url: 'https://api.github.com/repos/duy/canopy/downloads',
                    issues_url: 'https://api.github.com/repos/duy/canopy/issues{/number}',
                    pulls_url: 'https://api.github.com/repos/duy/canopy/pulls{/number}',
                    milestones_url: 'https://api.github.com/repos/duy/canopy/milestones{/number}',
                    notifications_url: 'https://api.github.com/repos/duy/canopy/notifications{?since,all,participating}',
                    labels_url: 'https://api.github.com/repos/duy/canopy/labels{/name}',
                    releases_url: 'https://api.github.com/repos/duy/canopy/releases{/id}',
                    deployments_url: 'https://api.github.com/repos/duy/canopy/deployments',
                    created_at: '2010-02-21T14:18:00Z',
                    updated_at: '2012-12-13T23:38:18Z',
                    pushed_at: '2009-11-10T16:15:40Z',
                    git_url: 'git://github.com/duy/canopy.git',
                    ssh_url: 'git@github.com:duy/canopy.git',
                    clone_url: 'https://github.com/duy/canopy.git',
                    svn_url: 'https://github.com/duy/canopy',
                    homepage: '',
                    size: 7632,
                    stargazers_count: 1,
                    watchers_count: 1,
                    language: null,
                    has_issues: false,
                    has_projects: true,
                    has_downloads: true,
                    has_wiki: true,
                    has_pages: false,
                    has_discussions: false,
                    forks_count: 1,
                    mirror_url: null,
                    archived: false,
                    disabled: false,
                    open_issues_count: 0,
                    license: null,
                    allow_forking: true,
                    is_template: false,
                    web_commit_signoff_required: false,
                    topics: [],
                    visibility: 'public',
                    forks: 1,
                    open_issues: 0,
                    watchers: 1,
                    default_branch: 'master',
                },
            ],
            username: 'duy',
        },
    ],
};
